### ISSUE TITLE
Procurement Process Updates

### ISSUE THREAD

**Issue by randyhart** [AlaskaDHSS/acq-alaska-dhss-modernization#151]
Once we know the final procurement timeline, we'll need to update this section of the RFP.
https://github.com/AlaskaDHSS/acq-alaska-dhss-modernization/blob/master/procurement-docs-search/Request-for-Proposals.md#sec-112-rfp-schedule

**Comment by randyhart** [comment]
Also this section.  https://github.com/AlaskaDHSS/acq-alaska-dhss-modernization/blob/master/procurement-docs-search/Request-for-Proposals.md#sec-103-deadline-for-receipt-of-proposals

**Comment by randyhart** [comment]
And this: https://github.com/AlaskaDHSS/acq-alaska-dhss-modernization/blob/master/procurement-docs-search/Request-for-Proposals.md#sec-106-questions-prior-to-deadline-for-receipt-of-proposals

**Comment by jongeselle** [comment]
Leave a comment
