### ISSUE TITLE
Link in RFP to summary of DevOps & Prototype Findings

### ISSUE THREAD

**Issue by randyhart** [AlaskaDHSS/acq-alaska-dhss-modernization#164]
In Section 3.01 of our draft RFP, we have the following statement.  The State of Alaska will provide documentation on how to access data sources, how to interact with existing authentication systems, and how to continuously deploy work to a staging environment.

@mheadd @waldoj @ctro & @sztaylorakgov this is where we'd want to link to the high-level findings you all have come across while setting up devops and the prototyping work you've done.

**Comment by mheadd** [comment]
Yes, we'll be able to provide language describing the various access methods for the different data sources, and also point to the prototype to show examples of how we did it - to provide a reference for vendors.
