### ISSUE TITLE
The Statement of Work should be deleted/archived.

### ISSUE THREAD

**Issue by randyhart** [AlaskaDHSS/acq-alaska-dhss-modernization#170]
The Statement of Work has been folded into the [draft RFP](https://github.com/AlaskaDHSS/acq-alaska-dhss-modernization/blob/master/procurement-docs-search/Request-for-Proposals.md) as needed.  In order to not confuse the vendors or make them read more than necessary, I suggest we archive/delete the working draft of the SOW.

**Comment by jongeselle** [comment]
I agree, though I'm not clear how to go about doing that.

**Comment by mheadd** [comment]
If we delete the file, it's just like committing any other change - we can create a new branch with the change, and when that chance is merged into `master` it will be removed from that branch. It will still exist in the git history, so we're not _really_ deleting it, and we (or a vendor) can go back and look at the file if they want.
