### ISSUE TITLE
Update technology preferences in DevOps.md file?

### ISSUE THREAD

**Issue by mheadd** [AlaskaDHSS/acq-alaska-dhss-modernization#222]
[This section](https://github.com/AlaskaDHSS/acq-alaska-dhss-modernization/blob/master/DevOps.md#environment) seems like it might be an earlier version. Are WindowsServer2016 and NanoServer relevant if we're using Azure. Since we're targeting .NET Core, do we care if development is done on Windows 10?

**Comment by ctro** [comment]
Wow, yeah. I need to fix that.  There's lots more backstory in the `DevSecOpsMVP` repo.  I'll correct/simplify the `DevOps.md` document here, and will point to the MVP repo when appropriate.

cc @mheadd

**Comment by mheadd** [comment]
Word. Thanks, @ctro!

**Comment by mheadd** [comment]
Resolved via [this PR](https://github.com/AlaskaDHSS/acq-alaska-dhss-modernization/pull/227).
